blueprints/user_mgmnt.py
import uuid
from flask import Blueprint, request, session, render_template, redirect, url_for
from models.logger import logger
from models.user import user


# Function to extract page title from path
def get_page_title(path):
    try: return path.split('.')[1]
    except: return path


bp = Blueprint('user', __name__)

@bp.route("/account", methods=["GET"])
def account():
    return render_template('account.html', page_title=get_page_title(request.endpoint))

# Route for registration
@bp.route("/register", methods=["GET", "POST"])
def register():
    error = None
    session.clear()
    user.clear()
    username = request.form.get('username', type=str, default=None)
    password = request.form.get('password', type=str, default=None)
    if request.method == "POST":
        status, message = user.find_by_username(username)
        if status and message is not None and message.get('user_id') is not None:
            error = 'username already exists'
        else:
            password = user.hash_password(password)
            user.populate(username=username, password=password)
            if user.push():
                return redirect(url_for('login'))
            else:
                error = 'something went wrong, you better check the logs'
    return render_template('register.html', page_title=get_page_title(request.endpoint), error=error, username=username)


@bp.route("/update/username", methods=["POST"])
def update_username():
    error = None
    username = request.form.get('username', type=str, default=None)
    
    status, message = user.find_by_username(username)
    
    if status and message is not None and message.get('user_id') is not None:
        error = 'username already exists'
    else:
        user.populate(username=username)
        if user.push():
            session['username'] = username
            logger.info(session)
            return 'success'
        else:
            error = 'internal error'
    return error

@bp.route("/update/password", methods=["POST"])
def update_password():
    error = None
    password = request.form.get('password', type=str, default=None)
    print(session)
    print(user.__dict__)
    
    # status, message = user.find_by_username(password)
    
    # if status and message is not None and message.get('user_id') is not None:
    #     error = 'username already exists'
    # else:
    #     user.populate(username=username)
    #     if user.push():
    #         session['username'] = username
    #         logger.info(session)
    #         return 'success'
    #     else:
    #         error = 'internal error'
    return ""

templates/account.html
{%-extends "base.html"-%}

{%-block head-%}
{%-endblock-%}

{%-block content-%}
<div class="row g-3 m-0 p-4 justify-content-center w-100">
    <div class="col-lg-12">
        <p class="fs-5 text-uppercase text-secondary text-center">Account</p>
    </div>
    <div class="w-100"></div>
    <form class="col-6" onsubmit="updateUsername(this); return false;">
        <label class="mb-2">Change username:</label>
        <div class="input-group mb-2">
            <span class="input-group-text"><i class="bi bi-person-fill"></i></span>
            <input name="username" class="form-control" type="text" placeholder="New username" required>
        </div>
        <div class="d-grid text-center">
            <button type="submit" class="btn">Update</button>
        </div>
    </form>

    <div class="w-100 my-4"></div>

    <form class="col-6" onsubmit="updatePassword(this); return false">
        <label class="mb-2">Change password:</label>
        <div class="input-group mb-4">
            <span class="input-group-text"><i class="bi bi-key"></i></span>
            <input name="password" class="form-control" type="password" placeholder="New password" required>
        </div>
        <div class="input-group mb-4 justify-content-center">
            <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
            <input name="password2" class="form-control" type="password" placeholder="Confirm Password" onkeyup="validatePassword()" required>
            <div class="w-100"></div>
            <div id="pass2-notice" class="text-danger" hidden>Passwords doesn't match</div>
        </div>
        <div class="d-grid text-center">
            <button type="submit" class="btn">Update Password</button>
        </div>
    </form>
</div>
{%-endblock-%}

{%-block footer-%}
<script>

    async function updateUsername(element) {
        let url = `{{url_for('user.update_username')}}`
        let response = await fetch(url, {method:'POST', body:new FormData(element)});
        let data = await response.text();
        console.log(data)
    }






    var pass1 = document.querySelector('input[name="password"]');
    var pass2 = document.querySelector('input[name="password2"]');
    var pass2_notice = document.getElementById('pass2-notice');
    function validatePassword() {
        if ( pass1.value === pass2.value ) {
            pass2_notice.hidden = true;
            return true;
        } else {
            pass2_notice.hidden = false;
            return false
        }
    }
    async function updatePassword(element) {
        if ( validatePassword() == true ) {
            let url = `{{url_for('user.update_password')}}`
            let response = await fetch(url, {method:'POST', body:new FormData(element)});
            let data = await response.text();
            console.log(data)
        }
    }
</script>
{%-endblock-%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ page_title.title() }} | Linkifyer</title>
        <meta name="description" content="Linkifyer is your go-to solution for effortlessly organizing and accessing your favorite web content. Save, categorize, and access your links anytime, anywhere.">
        <meta name="keywords" content="Linkifyer, links, web, organization, bookmarks, save links, browser">
        <meta name="author" content="Ricardo Basanez">
        <!-- For SEO -->
        <meta name="robots" content="index, follow">
        <meta name="googlebot" content="index, follow">
        <!-- For Open Graph -->
        <meta property="og:title" content="Linkifyer">
        <meta property="og:description" content="Linkifyer is your go-to solution for effortlessly organizing and accessing your favorite web content. Save, categorize, and access your links anytime, anywhere.">
        <meta property="og:image" content="{{ url_for('static', filename='img/web.png') }}">
        <meta property="og:url" content="">
        <meta property="og:type" content="website">
        <!-- For Twitter -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:title" content="Linkifyer">
        <meta name="twitter:description" content="Linkifyer is your go-to solution for effortlessly organizing and accessing your favorite web content. Save, categorize, and access your links anytime, anywhere.">
        <meta name="twitter:image" content="{{ url_for('static', filename='img/web.png') }}">
        <meta name="twitter:creator" content="@yourtwitterhandle">
        <!-- Favicon -->
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/icon_32.png') }}">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <!-- google fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        <!-- Local -->
        <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
        {%-block head-%}{%-endblock-%}
    </head>
    <body class="app-body">
        <div class="container-fluid d-flex flex-column">
            <!-- Navigation -->
            <div class="row p-2">
                <div class="col-12">
                    <nav class="navbar p-0 d-block d-lg-flex justify-content-between">
                        <div class="d-flex p-0 align-items-center">
                            <img src="{{ url_for('static', filename='img/icon_32.png') }}">
                            <p class="ps-2 fs-5">linkifyer</p>
                        </div>
                        <div class="d-flex p-0 justify-content-end align-items-center">
                            {%-if current_user.is_authenticated-%}
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Home" onclick="navigationTarget('home')"><h5><i class="bi bi-house"></i></h5></button>
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Library" onclick="navigationTarget('library')"><h5><i class="bi bi-collection"></i></h5></button>
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Account" onclick="navigationTarget('home')"><h5><i class="bi bi-person"></i></h5></button>
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="About" onclick="navigationTarget('home')" target="_blank"><h5><i class="bi bi-question"></i></h5></button>
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Log-out" onclick="navigationTarget('logout')"><h5><i class="bi bi-door-closed"></i></h5></button>
                            {%-else-%}
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Login" onclick="navigationTarget('login')"><h5><i class="bi bi-person-check"></i></h5></button>
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Register" onclick="navigationTarget('register')"><h5><i class="bi bi-person-add"></i></h5></button>
                            <button class="btn app-nav-btn" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="About" onclick="navigationTarget('home')" target="_blank"><h5><i class="bi bi-question"></i></h5></button>
                            {%-endif-%}
                        </div>
                    </nav>
                </div>
            </div>
            <!-- Main Content -->
            <div class="row p-2 pt-0">
                <div class="col-12 p-4 bg-white rounded">
                    <p class="fs-5 pb-4 text-center">{{page_title}}</p>
                    {%-block content-%}{%-endblock-%}
                </div>
                <div class="col-12 text-center text-lg-end">
                    <small>linkifyer v2.0</small>
                </div>
            </div>
        </div>
        <!-- Overlay -->
        <div id="overlay" style="display:block;"><div class="d-flex w-100 h-100 justify-content-center align-items-center"><div class="spinner-border" role="status"><span class="visually-hidden"></span></div><h1 class="ps-2"></h1></div></div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script src="{{url_for('static', filename='js/base.js')}}"></script>
        {%-for category, message in get_flashed_messages(with_categories=true)-%}
            <script>sendAlert(decodeURIComponent('{{message}}'), '{{category}}');</script>
        {%-endfor-%}
        {%-block footer-%}{%-endblock-%}
        <script>
            function navigationTarget ( target ) {
                switch (target) {
                    case 'home'     : window.location = `{{url_for('home')}}`; break;
                    case 'login'    : window.location = `{{url_for('login')}}`; break;
                    case 'library'    : window.location = `{{url_for('library')}}`; break;
                    case 'register' : window.location = `{{url_for('register')}}`; break;
                    case 'logout'   : window.location = `{{url_for('logout')}}`; break;
                    default: null;
                }
            }
        </script>
    </body>
</html>

templates/edit.html
{%-extends "base.html"-%}
{%-block head-%}{%-endblock-%}
{%-block content-%}

{%-set item_poster = item.poster if item.poster else 'img/img_404.jpg'-%}
{%-set item_poster = url_for('static', filename=item_poster)-%}
{%-set item_icon = item.icon if item.icon else 'img/icon_404.png'-%}
{%-set item_icon = url_for('static', filename=item_icon)-%}

    {%-macro render_field(field)-%}
        {{ field(**kwargs)|safe }}
        {%-if field.errors-%}
            {%-for error in field.errors-%}
                <div class="w-100 text-danger ps-5">* {{ error }}</div>
            {%-endfor-%}
        {%-endif-%}
    {%-endmacro-%}

    <div class="row m-0 py-4 justify-content-center">
        <div class="col-lg-auto text-center mb-2 mb-lg-0"><img class="img-fluid rounded" src="{{item_poster}}" alt=""></div>
        <form method="POST" onsubmit="submitFormData(this);return false;" class="col-lg">
            {{form.hidden_tag()}}
            {{ render_field(form.hash) }}
            {{ render_field(form.poster) }}
            {{ render_field(form.icon) }}
            {{ render_field(form.host) }}
            {{ render_field(form.schema) }}
            {{ render_field(form.url) }}
            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Title (editable)">
                <span class="input-group-text"><i class="bi bi-chat-square"></i></span>
                {{ render_field(form.title) }}
            </div>
            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Description (editable)">
                <span class="input-group-text"><i class="bi bi-card-text"></i></span>
                {{ render_field(form.description) }}
            </div>

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Tags">
                <span class="input-group-text"><i class="bi bi-tags"></i></span>
                <div id="tag-container" class="form-control">
                    {{ render_field(form.tags) }}
                </div>
            </div>

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Models">
                <span class="input-group-text"><i class="bi bi-people"></i></span>
                <div id="actor-container" class="form-control">
                    {{ render_field(form.model) }}
                </div>
            </div>

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Collections">
                <span class="input-group-text"><i class="bi bi-folder"></i></span>
                <div id="collection-container" class="form-control">
                    {{ render_field(form.collections) }}
                </div>
            </div>

            <div class="d-grid">
                <button type="submit" class="btn app-btn" text-white>Save</button>
            </div>
            <div class="text-center"><span id="error" class="mt-2 text-danger"></span></div>
        </form>
    </div>

{%-endblock-%}
{%-block footer-%}

<script>

    const constructBadges = (value, container) => {
        value.split(',').map( item => {
            if (item.trim().length > 0) {
                let span = document.createElement('span')
                span.setAttribute('class','badge text-bg-danger m-1')
                span.innerHTML = `
                    <span class="d-flex align-items-center">
                        ${item.trim()}
                        <button class="btn-close ms-1" data-app-delete="badge" onclick="this.parentNode.parentNode.remove();"></button>
                    </span>`.trim()
                container.insertBefore(span, container.lastElementChild)
            }
        });
    }

    const clearInput = (elem) => {
        elem.value = '';
        elem.setAttribute('value', '');
        return elem
    }

    var model = document.getElementById('model')
    var actorContainer = document.getElementById('actor-container')
    constructBadges(model.value, actorContainer);
    model = clearInput(model);
    model.addEventListener('input', function() {
        if ( this.value.includes(',') ) {
            constructBadges(this.value, actorContainer);
            model = clearInput(model);
        }
    })

    var tags = document.getElementById('tags')
    var tagContainer = document.getElementById('tag-container')
    constructBadges(tags.value, tagContainer);
    tags = clearInput(tags);
    tags.addEventListener('input', function() {
        if ( this.value.includes(',') ) {
            constructBadges(this.value, tagContainer);
            tags = clearInput(tags);
        }
    })


    var collections = document.getElementById('collections')
    var collectionContainer = document.getElementById('collection-container')
    constructBadges(collections.value, collectionContainer);
    collections = clearInput(collections);
    collections.addEventListener('input', function() {
        if ( this.value.includes(',') ) {
            constructBadges(this.value, collectionContainer);
            collections = clearInput(collections);
        }
    })

    function submitFormData(form) {
        $("#overlay").show();
        let tagValue = [...new Set(tagContainer.innerText.split('\n').map( item => { if (item.trim().length > 0) { return item.trim() }; }))].sort() .join(',');
        tags.value = tagValue;
        let actorValue = [...new Set(actorContainer.innerText.split('\n').map( item => { if (item.trim().length > 0) { return item.trim() }; }))].sort() .join(',');
        model.value = actorValue;
        let collectionValue = [...new Set(collectionContainer.innerText.split('\n').map( item => { if (item.trim().length > 0) { return item.trim() }; }))].sort() .join(',');
        collections.value = collectionValue;
        form.submit();
    }




</script>

{%-endblock-%}

templates/fetch.html
{%-extends "base.html"-%}
{%-block head-%}{%-endblock-%}
{%-block content-%}

    {%-macro render_field(field)-%}
        {{ field(**kwargs)|safe }}
        {%-if field.errors-%}
            {%-for error in field.errors-%}
                <div class="w-100 text-danger ps-5">* {{ error }}</div>
            {%-endfor-%}
        {%-endif-%}
    {%-endmacro-%}

    <div class="row m-0 py-4 justify-content-center">
        <div class="col-lg-auto text-center mb-2 mb-lg-0">
            <img class="img-fluid rounded" src="{{item.poster_url}}" style="max-width:600px;max-height:600px;">
            <p class="text-start"><small><img src="{{item.icon_url}}" width="16"> <a href="{{item.host}}" target="_blank" class="text-decoration-none">{{item.host}}</small></a></p>
        </div>
        <form method="POST" onsubmit="submitFormData(this);return false;" class="col-lg">
            {{ form.hidden_tag() }}
            {{ render_field(form.hash) }}
            {{ render_field(form.poster_url) }}
            {{ render_field(form.poster_path) }}
            {{ render_field(form.icon_url) }}
            {{ render_field(form.icon_path) }}
            {{ render_field(form.host) }}
            {{ render_field(form.url) }}

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Title (editable)">
                <span class="input-group-text"><i class="bi bi-chat-square"></i></span>
                {{ render_field(form.title) }}
            </div>

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Description (editable)">
                <span class="input-group-text"><i class="bi bi-card-text"></i></span>
                {{ render_field(form.description) }}
            </div>

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Tags">
                <span class="input-group-text"><i class="bi bi-tags"></i></span>
                <div id="tag-container" class="form-control">
                    {{ render_field(form.tags) }}
                </div>
            </div>

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Models">
                <span class="input-group-text"><i class="bi bi-people"></i></span>
                <div id="actor-container" class="form-control">
                    {{ render_field(form.models) }}
                </div>
            </div>

            <div class="input-group mb-2" data-bs-toggle="tooltip" data-bs-title="Collections">
                <span class="input-group-text"><i class="bi bi-folder"></i></span>
                <div id="collection-container" class="form-control">
                    {{ render_field(form.collections) }}
                </div>
            </div>

            <div class="d-grid">
                <button type="submit" class="btn app-btn" text-white>Save</button>
            </div>
            <div class="text-center"><span id="error" class="mt-2 text-danger"></span></div>
        </form>
    </div>

{%-endblock-%}
{%-block footer-%}

<script>

    const constructBadges = (value, container) => {
        value.split(',').map( item => {
            if (item.trim().length > 0) {
                let span = document.createElement('span')
                span.setAttribute('class','badge text-bg-danger m-1')
                span.innerHTML = `
                    <span class="d-flex align-items-center">
                        ${item.trim()}
                        <button class="btn-close ms-1" data-app-delete="badge" onclick="this.parentNode.parentNode.remove();"></button>
                    </span>`.trim()
                container.insertBefore(span, container.lastElementChild)
            }
        });
    }

    const clearInput = (elem) => {
        elem.value = '';
        elem.setAttribute('value', '');
        return elem
    }

    var model = document.getElementById('model')
    var actorContainer = document.getElementById('actor-container')
    constructBadges(model.value, actorContainer);
    model = clearInput(model);
    model.addEventListener('input', function() {
        if ( this.value.includes(',') ) {
            constructBadges(this.value, actorContainer);
            model = clearInput(model);
        }
    })

    var tags = document.getElementById('tags')
    var tagContainer = document.getElementById('tag-container')
    constructBadges(tags.value, tagContainer);
    tags = clearInput(tags);
    tags.addEventListener('input', function() {
        if ( this.value.includes(',') ) {
            constructBadges(this.value, tagContainer);
            tags = clearInput(tags);
        }
    })

    var collections = document.getElementById('collections')
    var collectionContainer = document.getElementById('collection-container')
    constructBadges(collections.value, collectionContainer);
    collections = clearInput(collections);
    collections.addEventListener('input', function() {
        if ( this.value.includes(',') ) {
            constructBadges(this.value, collectionContainer);
            collections = clearInput(collections);
        }
    })

    function submitFormData(form) {
        $("#overlay").show();
        let tagValue = [...new Set(tagContainer.innerText.split('\n').map( item => { if (item.trim().length > 0) { return item.trim() }; }))].sort() .join(',');
        tags.value = tagValue;
        let actorValue = [...new Set(actorContainer.innerText.split('\n').map( item => { if (item.trim().length > 0) { return item.trim() }; }))].sort() .join(',');
        model.value = actorValue;
        let collectionValue = [...new Set(collectionContainer.innerText.split('\n').map( item => { if (item.trim().length > 0) { return item.trim() }; }))].sort() .join(',');
        collections.value = collectionValue;


        const urlParams = new URLSearchParams(window.location.search);
        const existingWValue = urlParams.get('w');
        if (existingWValue) {
            form.setAttribute('action', `?w=${existingWValue}`);
        }
        form.submit();
    }




</script>

{%-endblock-%}

templates/home.html
{%-extends "base.html"-%}
{%-block head-%}{%-endblock-%}
{%-block content-%}
    {%-macro render_field(field)-%}
    <div class="form-floating">
        {{ field(**kwargs)|safe }}
        <label for="{{field.id}}">{{ field.label.text|safe }}
        </label>
    </div>
    {%-endmacro-%}
    <div class="row m-0 justify-content-center">
        <div class="col-lg-6">
            <form action="{{url_for('fetch')}}" method="GET" onsubmit="submitForm(this);return false;">
                <div class="input-group">
                    <span class="input-group-text"><i class="bi bi-link"></i></span>
                    {{ render_field(form.url) }}
                    <button type=submit class="btn app-btn"><i class="bi bi-binoculars-fill"></i></button>
                </div>
            </form>
        </div>
    </div>
{%-endblock-%}
{%-block footer-%}{%-endblock-%}

templates/library.html
{%-extends "base.html"-%}
{%-block head-%}
    <style>
        .cover {
            background-repeat: no-repeat;
            background-size: cover;
        }
        .cover a {
            background-color:rgba(0, 0, 0, 0.5);
            color: white;
            text-decoration: none;
        }
    </style>
{%-endblock-%}

{%-block content-%}
    {%-macro render_field(field)-%}
    <div class="form-floating">
        {{ field(**kwargs)|safe }}
        <label for="{{field.id}}">{{ field.label.text|safe }}
        </label>
    </div>
    {%-endmacro-%}
    <div class="row justify-content-center">

        <div class="col-lg-12 mb-3">
            <div id="paginationTop" class="input-group m-0 justify-content-center"></div>
        </div>
        <div class="col-lg-6 mb-3">
            <form action="{{url_for('fetch')}}?w={{page_title}}" method="GET" onsubmit="submitForm(this);return false;">
                <div class="input-group">
                    <span class="input-group-text"><i class="bi bi-link"></i></span>
                    {{ render_field(form.url) }}
                    <button type=submit class="btn app-btn"><i class="bi bi-binoculars-fill"></i></button>
                </div>
            </form>
        </div>

        <div class="w-100"></div>
        <div class="col-lg-6">
            <div class="input-group">
                <div class="form-floating force">
                    <input id="filter-input" type="text" class="form-control" placeholder="">
                    <label for="filter-input">Filter</label>
                </div>
                <div class="form-floating">
                    <select id="filter-model" class="form-select">
                        <option value="" selected></option>
                    </select>
                    <label for="ilter-model">Models</label>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div id="items" class="row row-cols-1 row-cols-lg-6 g-3 m-0 justify-content-center">
            </div>
        </div>
        <div class="col-lg-12 mt-3">
            <div id="paginationBottom" class="input-group justify-content-center"></div>
        </div>
    </div>
{%-endblock-%}

{%-block footer-%}
    <script>
        var ITEMS_ALL = [];
        var ITEMS_FILTERED = [];
        var ITEMS_PER_PAGE = 24;
        var PAGE_CURRENT = 1
        var PAGES_TOTAL = 1;
    </script>
    <script src="{{url_for('static', filename='js/library.js')}}"></script>
    <script>

        let toggleStatus = null;
        function toggleVisible(status) {
            if ( toggleStatus == status ) { return; }
            event.srcElement.firstElementChild.classList.toggle('d-none');
            toggleStatus = status;
        }

        async function actionDelete(id) {
            if ( confirm("are you shure you want to delete your link?") ) {
                let response = await fetch(`{{url_for('delete')}}/${id}`);
                result = await response.text();
                if ( result == 1 ) {
                    ITEMS_ALL = ITEMS_ALL.filter( item => item.id != id );
                    ITEMS_FILTERED = ITEMS_ALL;
                    updatePagination(PAGE_CURRENT);
                }
            }
        }


        function actionEdit(id) {
            $("#overlay").show();
            window.location = `{{url_for('edit')}}/${id}`;
        }

        function actionFetch(url) {
            $("#overlay").show();
            window.location = `{{url_for('fetch')}}?link=${url}`;
        }

        function actionGoTo(url) {
            $("#overlay").show();
            window.open(url, '_blank');
        }



        loadItems(`{{url_for('items', id='all')}}`);
    </script>
{%-endblock-%}

templates/login.html
{%-extends "base.html"-%}
{%-block head-%}{%-endblock-%}
{%-block content-%}


    {%-macro render_field(field)-%}
        <div class="form-floating mb-2">
            {{ field(**kwargs)|safe }}
            <label for="{{field.id}}">
                {%-if field.errors-%}
                    {%-for error in field.errors-%}
                        <div class="w-100 text-danger">* {{ error }}</div>
                    {%-endfor-%}
                {%-else-%}
                    {{ field.label.text|safe }}
                {%-endif-%}
            </label>
        </div>
    {%-endmacro-%}

    <div class="row justify-content-center">
    <form class="col-lg-4" method="POST" onsubmit="submitForm(this);return false;">
        {{form.hidden_tag()}}
        {{ render_field(form.username) }}
        {{ render_field(form.password) }}
        <div class="d-grid">
            <button type="submit" class="btn app-btn">Login</button>
        </div>
    </form>
</div>
    <script>
    const myModalAlternative = new bootstrap.Modal('#modal-login', {})
    // myModalAlternative.show();
    </script>



{%-endblock-%}
{%-block footer-%}
{%-endblock-%}